name: Node.js Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd Login/package-lock.json  # Navigate to the root directory of your repository
          npm ci

      - name: Build
        run: |
          cd ECOMM-CASSY/Login/  # Navigate to the root directory of your repository
          nodemon src/index.js

      - name: Start server
        run: |
          cd ECOMM-CASSY/Login/  # Navigate to the root directory of your repository
          npm start
